### Numpy:
           - Numpy stands for numerical python.
           - It is mainly used for to create the N-dimensional arrays.
           - first we need to import numpy.
- How to create the numpy array:
    * using list,tuple,diciotnary,range and arange function..
- syntax of numpy array:
    * variable_name = numpy.array(list,tuple,diciotnary)

In [1]:
# import numpy array..
import numpy as np

In [3]:
print(dir(np))
print(len(dir(np)))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__sp

In [5]:
# To know the current version?
np.__version__

'1.20.1'

In [7]:
# To create the 1-d numpy array using List?
n1 = np.array([10,20,30,40])
print(n1)
print(type(n1))

[10 20 30 40]
<class 'numpy.ndarray'>


In [9]:
# To create the 2-d numpy array using list?
n2 = np.array([[1,2,3],[4,5,6]])
print(n2)
print(type(n2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [17]:
# Attributes of numpy array...
print(n2)
print(n2.shape) # TO get the number of rows and columns
print(n2.ndim) # TO get the dimensions
print(n1.ndim)
print(n2.size) # To get the number of elements
print(n2.dtype)
print(n2.itemsize)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
1
6
int32
4


In [25]:
n1 = np.array([1,45.67])
print(n1.itemsize)
print(n1.dtype)

8
float64


In [27]:
# To create the numpy array using tuple...
np.array((10,20,30))

array([10, 20, 30])

In [29]:
# To create the numpy array using dictionary...
d1 = np.array({'Name':'Aaryan','Rno':419,'Branch':'ECE'})
print(d1)
print(type(d1))

{'Name': 'Aaryan', 'Rno': 419, 'Branch': 'ECE'}
<class 'numpy.ndarray'>


In [30]:
# To create the numpy array using range function...
n3 = np.array(range(10,20))
print(n3)

[10 11 12 13 14 15 16 17 18 19]


In [31]:
# To create the numpy array using arange function..
n4 = np.arange(10,20)
print(n4)

[10 11 12 13 14 15 16 17 18 19]


In [33]:
# range: Inbuilt function in python
# arange: inbuilt function in numpy array
print(np.array(range(1.5,10.5)))

TypeError: 'float' object cannot be interpreted as an integer

In [34]:
print(np.arange(1.5,10.5))

[1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]


In [36]:
# linspace..
n = np.linspace(1,10)
print(n)
print(n.ndim)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
1


In [40]:
n2 = np.linspace(10,30,6,dtype=int)
print(n2)

[10 14 18 22 26 30]


In [42]:
# To change the data type ...
print(np.array([10,20,30],dtype=float))

[10. 20. 30.]


### Array Initialization:

In [44]:
# using zeros method to create the 1-d array
a1 = np.zeros(5,dtype=int)
print(a1)

[0 0 0 0 0]


In [46]:
# TO create the 2-d array...
a2 = np.zeros((2,4),dtype=int)
print(a2)

[[0 0 0 0]
 [0 0 0 0]]


In [48]:
np.empty((2,5))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        7.56595733e-307, 6.23053614e-307],
       [8.45593934e-307, 7.56593017e-307, 1.11258854e-306,
        2.22522597e-306, 8.34444713e-308]])

In [51]:
# using ones method 
print(np.ones(10)) # 1-d array
print(np.ones((3,3),dtype=int)) # 2-d array

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [53]:
# To print the identity matrix..
print(np.eye((4),dtype=int))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [57]:
print(np.identity((3),dtype=int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [58]:
# To print the diagonal values..
print(np.diag([4,5,6,7]))

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 7]]


In [59]:
# To print the one specific ...
print(np.full(4,7))

[7 7 7 7]


In [60]:
print(np.full((2,2),5))

[[5 5]
 [5 5]]


In [64]:
# Arithmetic operations:
n1 = np.array([[1,2],[3,4]])
n2 = np.array([[2,3],[5,6]])
print('n1 matrix is: ')
print(n1)
print('n2 matrix is: ')
print(n2)
print('Addition is: ',n1+n2)
print('Multiplication is: ')
print(n1*n2) # Element wise product..

n1 matrix is: 
[[1 2]
 [3 4]]
n2 matrix is: 
[[2 3]
 [5 6]]
Addition is:  [[ 3  5]
 [ 8 10]]
Multiplication is: 
[[ 2  6]
 [15 24]]


In [65]:
print('Matrix multiplication is: ')
print(n1.dot(n2))

Matrix multiplication is: 
[[12 15]
 [26 33]]


### random():
- It is one of the submodule in numpy.
- It is mainly used to generate the random elements in between range.

In [67]:
# sub module in numpy:
rn = np.random
print(dir(rn))

['BitGenerator', 'Generator', 'MT19937', 'PCG64', 'Philox', 'RandomState', 'SFC64', 'SeedSequence', '__RandomState_ctor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_bounded_integers', '_common', '_generator', '_mt19937', '_pcg64', '_philox', '_pickle', '_sfc64', 'beta', 'binomial', 'bit_generator', 'bytes', 'chisquare', 'choice', 'default_rng', 'dirichlet', 'exponential', 'f', 'gamma', 'geometric', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'pareto', 'permutation', 'poisson', 'power', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uni

In [72]:
# To generate the single random integer..
print(np.random.randint(20,30))

25


In [74]:
# To generate the n number of random numbers..
print(np.random.randint(10,20,4)) # 4 numbers

[19 10 11 19]


In [77]:
# To generate the 2-d numpy array using random..
print(np.random.randint(10,20,(5,5)))

[[15 14 18 18 16]
 [12 10 14 19 10]
 [10 17 13 18 19]
 [19 11 14 17 13]
 [16 15 19 10 19]]


In [78]:
print(np.random.randn(4,3))
# It creates the -ve random integers from i.e -1

[[-1.68422731 -0.35215338  0.72442284]
 [-0.63456382 -0.82669068 -0.11802728]
 [-0.73625061 -2.18415306 -0.8613008 ]
 [ 0.79932484 -0.73355827 -1.7079773 ]]


In [79]:
print(np.random.rand(2,2))
# It create the random array of digits starts from 0.

[[0.29399521 0.84615836]
 [0.74483195 0.19950854]]


### indexing:

In [80]:
n = np.random.randint(10,50,(4,4))
print(n)

[[27 12 36 22]
 [12 12 24 32]
 [45 27 29 11]
 [16 49 46 20]]


In [84]:
print(n[0])# To get the first row
print(n[-1]) # To get the last row
print(n[0,1]) # To get specific value
print(n[::-1]) # To print the reverse numpy array

[27 12 36 22]
[16 49 46 20]
12
[[16 49 46 20]
 [45 27 29 11]
 [12 12 24 32]
 [27 12 36 22]]


#### boolean indexing and fancy indexing:
- boolean indexing: It will return the boolean values like true or false based on our condition.
- Fancy indexing: It will return the value..

In [85]:
print(n)

[[27 12 36 22]
 [12 12 24 32]
 [45 27 29 11]
 [16 49 46 20]]


In [88]:
# Boolean indexing:
# To get the even elements from a numpy array..
print(n%2==0)

[[False  True  True  True]
 [ True  True  True  True]
 [False False False False]
 [ True False  True  True]]


In [89]:
# fancy indexing:
# To get the even values..
print(n[n%2==0])

[12 36 22 12 12 24 32 16 46 20]


### reshape:
        - To convert the 1-d array to n-d array..

In [91]:
n1 = np.arange(10).reshape(2,5)
print(n1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [92]:
print(np.arange(4).reshape(2,2))

[[0 1]
 [2 3]]


In [93]:
print(np.arange(15).reshape(3,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [94]:
print(np.arange(10).reshape(5,-1))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [95]:
print(np.arange(12).reshape(4,-1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


#### resize:
        - To resize the numpy array.

In [100]:
n1 = np.arange(10).reshape(5,2)
print(n1)
print('Resize the numpy array: ')
print(np.resize(n1,(2,2)))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Resize the numpy array: 
[[0 1]
 [2 3]]


In [101]:
print(n1)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [103]:
n2 = np.arange(10)
print(n2)
print(np.resize(n2,(2,2)))

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]]
