In [1]:
import numpy as np

In [2]:
n1 = np.arange(10).reshape(2,5)
print(n1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [4]:
np.arange(16).reshape(8,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [7]:
np.arange(16).reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

### stacking: 
        - vstack -> we can add rows
        - hstack -> to add columns

In [10]:
a1 = np.random.randint(1,10,(2,1))
print(a1)
b1 = np.random.randint(1,10,(2,1))
print(b1)
print('--vstack---')
print(np.vstack((a1,b1)))
print('-------------------------')
print(a1)

[[7]
 [9]]
[[6]
 [4]]
--vstack---
[[7]
 [9]
 [6]
 [4]]
-------------------------
[[7]
 [9]]


In [12]:
# example on hstack..
a2 = np.random.randint(1,10,(2,2))
b2 = np.random.randint(1,10,(2,2))
print('----hstack----------')
print(np.hstack((a2,b2)))

----hstack----------
[[7 3 1 5]
 [7 9 4 5]]


#### ravel() and flatten():
            - To convert the numpy array into n-dimensional to 1-dimensional.    

In [17]:
# example on ravel().
a = np.array([[1,2],[3,4]])
print('Original Array...')
print(a)
print('Dimensions is:',a.ndim)
b = a.ravel()
print(b)
print('b dimensions: ',b.ndim)
b[0] = 100
print(b)
print('original a numpy array: ')
print(a)

Original Array...
[[1 2]
 [3 4]]
Dimensions is: 2
[1 2 3 4]
b dimensions:  1
[100   2   3   4]
original a numpy array: 
[[100   2]
 [  3   4]]


In [20]:
# example on flatten():
a1 = np.array([[4,5],[7,8]])
print(a1)
b2 = a1.flatten()
print(b2)
b2[1]=45
print(b2)
print('To print the original array: ')
print(a1)

[[4 5]
 [7 8]]
[4 5 7 8]
[ 4 45  7  8]
To print the original array: 
[[4 5]
 [7 8]]


### Data Analysis and Pandas:

- Pandas Introduction:
    - Pandas stands for 'Python Data Analysis Library'.
    - It is open source library.
    - It is Excellent tool for Data processing and Analyzing of real world data.

- Pandas has two different data Stuctures:
- 1. Series Data Structure
- 2. DataFrame data Structure

- 1. Series Data Structure:
        - It is mainly used for to create the 1-d dimensional array with named index..

- 2. DataFrame Data Structure:
        - It is mainly used for to create the 2-d dimensional array in the format of rows and columns.
        
- Pandas is mainly used for data analysis and data manipulations.
- By using pandas we read the large amount of data like.., excel,csv,tabular..

- 1. How to installing and importing pandas?
- IDLE prefer with pip? pip install pandas
- Importing library: import pandas as pd

### Series Data Structure:
    - Creating Series object using list,tuple,dicitonary and also numpy array.
    
    - Create pandas Series from array-like object using pd.Series()
    
    - syntax: pd.Series(list,tuple,dict,numpy_array,indexnames)
    
    - The number of elements in the index list is always equal to the number of elements in the specified series.

In [21]:
import pandas as pd

In [22]:
# Creation of Series data structure using list?
L1 = [10,20,30]
sd1 = pd.Series(L1)
print(sd1)
print(type(sd1))

0    10
1    20
2    30
dtype: int64
<class 'pandas.core.series.Series'>


In [25]:
# To change the index names..
sd1.index = ['A','B','C']
sd1

A    10
B    20
C    30
dtype: int64

In [26]:
sd2 = pd.Series([23,'python',34.5,89],index=['A','B','C','D'])
print(sd2)

A        23
B    python
C      34.5
D        89
dtype: object


In [27]:
# To create the Series using numpy array?
np1 = np.array([10,20,30])
s2 = pd.Series(np1)
s2

0    10
1    20
2    30
dtype: int32

In [28]:
# Creation of Series using Dictionary?
d1 = {'Name':'Aadyan','Rno':510,'Branch':'CSE'}
sd3 = pd.Series(d1)
print(sd3)

Name      Aadyan
Rno          510
Branch       CSE
dtype: object


In [30]:
# creation of series using tuple..
sd4 = pd.Series((10,20,30))
print(sd4)

0    10
1    20
2    30
dtype: int64


### Series Indexing:
- To get the data from the series..
- TO access the values from a series using index names..

In [31]:
sd2 = pd.Series([10,20,30,'apssdc',45.6,'Python'])
print(sd2)

0        10
1        20
2        30
3    apssdc
4      45.6
5    Python
dtype: object


In [33]:
# To access the value from a series..
sd2[2]

30

In [34]:
sd3

Name      Aadyan
Rno          510
Branch       CSE
dtype: object

In [35]:
sd3['Name']

'Aadyan'

In [37]:
sd2[::2] # To get the alternative rows

0      10
2      30
4    45.6
dtype: object

In [38]:
sd2[:3]

0    10
1    20
2    30
dtype: object

In [39]:
sd2[::-1]

5    Python
4      45.6
3    apssdc
2        30
1        20
0        10
dtype: object

In [41]:
sd2[0]

10