### Data Preprocessing with Scikit learn

#### Preprocessing Techniques

* Data Preprocessing is a technique that is used to convert raw data into a clean dataset

### Data preprocessing steps

* Loading data (reading files)
* Exploring data (Summarizing,statistics etc..)
* Cleaning data (handling missing data)
* Transforming data (Scaling ,feature engineering etc..)
        * will learn data preprocessing technique with scikit-learn,one of the most popular frameworks used for DataScience
        * The scikit-learn library include tools for data preprocessing and data mining. 
        * It is imported in python via statement import sklearn
        * provides machine learning algorithms: classification,regression,clustering,model validation etc
        * scikitlearn built on Numpy,Scipy and Matplotlib
    


### Data Imputation( used to deal with mising values)

* Data imputation is a method for retaining the majority of dataset's set and information by substituting missing data with a different value.
* if the dataset is missing too many values,we just don't use it
* if only a few of the values are missing, we can perform data imputation to substitute the missing data with some other values
* There are many different methods for data imputation
    * Using the mean value
    * Using the median value
    * Using the most frequent value(mode)
    * Filling missing values with a constant


### Data  imputation

In [1]:
from sklearn.impute import SimpleImputer

In [5]:
import pandas as pd
import numpy as np
di={
    "a":pd.Series([10,89,76,np.nan,56],index=[1,2,3,4,5]),
    "b":pd.Series([454,34,23,34],index=[1,3,4,5]),
    "c":pd.Series([13,45,35,35],index=[1,2,3,4])
}
df=pd.DataFrame(di)
df

a      b     c
1  10.0  454.0  13.0
2  89.0    NaN  45.0
3  76.0   34.0  35.0
4   NaN   23.0  35.0
5  56.0   34.0   NaN

* fit_transform() from sklearn,preprocessing class is  used to preprocessing data for 
model training
* fit() method calculates various required parameters and
* transform() method applies the calculated parameters to standardize the data
* The fit_transform() is used to fit the data into a model and transform it into a form that is more suitable for model in a single step. This saves our time and effort for calling both fit() and transform() seperately

In [6]:
si=SimpleImputer(strategy="median")
si.fit_transform(df)

array([[ 10., 454.,  13.],
       [ 89.,  34.,  45.],
       [ 76.,  34.,  35.],
       [ 66.,  23.,  35.],
       [ 56.,  34.,  35.]])

In [7]:
df.median()

a    66.0
b    34.0
c    35.0
dtype: float64

In [8]:
si=SimpleImputer(strategy="mean")
si.fit_transform(df)

array([[ 10.  , 454.  ,  13.  ],
       [ 89.  , 136.25,  45.  ],
       [ 76.  ,  34.  ,  35.  ],
       [ 57.75,  23.  ,  35.  ],
       [ 56.  ,  34.  ,  32.  ]])

In [9]:
df.mean()

a     57.75
b    136.25
c     32.00
dtype: float64

In [11]:
si=SimpleImputer(strategy="most_frequent")
si.fit_transform(df)

C:\Users\meena\anaconda3\lib\site-packages\sklearn\impute\_base.py:49: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode = stats.mode(array)


array([[ 10., 454.,  13.],
       [ 89.,  34.,  45.],
       [ 76.,  34.,  35.],
       [ 10.,  23.,  35.],
       [ 56.,  34.,  35.]])

In [12]:
si=SimpleImputer(strategy="constant",fill_value=-1)
si.fit_transform(df)

array([[ 10., 454.,  13.],
       [ 89.,  -1.,  45.],
       [ 76.,  34.,  35.],
       [ -1.,  23.,  35.],
       [ 56.,  34.,  -1.]])

# Task 
* Load titanic dataset
* clean data by using simpleimputer

In [ ]:
[10kg ,1000 tones , 70 gms, 800 gms] --- weights

10+1000+70+800  -->in correct

* Inorder to do sum of weights we have to convert all units into same unit or unique format ,
this is nothing but scaling

### Feature scaling

* Feature scaling is a data preprocessing technique that involves transforming the values of features
or variables in a dataset into a similar scale.
* Feature scaling  is the process of normalizing the range of features in a dsataset
* Real world data often contain features that are varying in degrees of magnitude,range and units
* Therefore inorder for machine learning models to interpret these features on the same scale ,
we need to perform feature scaling

### Scaling techniques 
* used to convert raw data into meaningful data
1. Standardizing Data
2. Data Range
3. Normalizing Data
4. Robust scaling

### 1.Standardizing data(column wise or label wise or feature wise)

* Standard format refers to data that has 0 mean and unit variance(i.e standard deviation=1), and the process of converting data into this format is called data standardization
